# This docker-compose file will spin up an ACS cluster on a local host or on a server and it requires a minimum of 12GB Memory to distribute among containers.
# Limit container memory and assign X percentage to JVM.  There are couple of ways to allocate JVM Memory for ACS Containers
# For example: 'JAVA_OPTS: "$JAVA_OPTS -XX:+PrintFlagsFinal -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"'
# See Oracle docs (https://docs.oracle.com/javase/9/gctuning/parallel-collector1.htm#JSGCT-GUID-CAB83393-3438-44ED-98F0-D15641B43C7D).
# If the container memory is not explicitly set then the flags above will set the max heap default to 1/4 of the container's memory, which may not be ideal.
# For performance tuning, assign the container memory and give a percentage of it to the JVM.

# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "2"

services:
    alfresco:
        image: alfresco/alfresco-content-repository-community:$ALFRESCO_TAG
        container_name: "${PROJECT_NAME}_alfresco"
        mem_limit: 1500m
        volumes:
            - ./volumes/data/alf-repo-data:/usr/local/tomcat/alf_data
            - ./volumes/logs/alfresco:/usr/local/tomcat/logs
            # - ./volumes/config/alfresco-global.properties:/usr/local/tomcat/shared/classes/alfresco-global.properties
        environment:
            JAVA_OPTS: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=${DB_NAME}
                -Ddb.password=${DB_PASSWORD}
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=127.0.0.1
                -Dshare.port=8080
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=DOCKER_COMPOSE

                -Dlocal.transform.service.enabled=true
                -DlocalTransform.pdfrenderer.url=http://alfresco-pdf-renderer:8090/
                -DlocalTransform.imagemagick.url=http://imagemagick:8090/
                -DlocalTransform.libreoffice.url=http://libreoffice:8090/
                -DlocalTransform.tika.url=http://tika:8090/
                -DlocalTransform.misc.url=http://transform-misc:8090/

                -Dlegacy.transform.service.enabled=true
                -Dalfresco-pdf-renderer.url=http://alfresco-pdf-renderer:8090/
                -Djodconverter.url=http://libreoffice:8090/
                -Dimg.url=http://imagemagick:8090/
                -Dtika.url=http://tika:8090/
                -Dtransform.misc.url=http://transform-misc:8090/

                -Dcsrf.filter.enabled=false
                -Xms1500m -Xmx1500m
                "

    alfresco-pdf-renderer:
        image: alfresco/alfresco-pdf-renderer:$PDF_RENDERER_TAG
        container_name: "${PROJECT_NAME}_alfresco-pdf-renderer"
        mem_limit: 1g
        # environment:
        #     JAVA_OPTS: " -Xms256m -Xmx512m"
        # ports:
        #     - 8090:8090

    imagemagick:
        image: alfresco/alfresco-imagemagick:$IMAGEMAGICK_TAG
        container_name: "${PROJECT_NAME}_imagemagick"
        mem_limit: 1g
        # environment:
        #     JAVA_OPTS: " -Xms256m -Xmx512m"
        # ports:
        #     - 8091:8090

    libreoffice:
        image: alfresco/alfresco-libreoffice:$LIBRE_OFFICE_TAG
        container_name: "${PROJECT_NAME}_libreoffice"
        mem_limit: 1g
        # environment:
        #     JAVA_OPTS: " -Xms256m -Xmx512m"
        # ports:
        #     - 8092:8090

    tika:
        image: alfresco/alfresco-tika:$TIKA_TAG
        container_name: "${PROJECT_NAME}_tika"
        mem_limit: 1g
        # environment:
        #     JAVA_OPTS: " -Xms256m -Xmx512m"
        # ports:
        #     - 8093:8090

    transform-misc:
        image: alfresco/alfresco-transform-misc:$TRANSFORM_TAG
        container_name: "${PROJECT_NAME}_transform"
        mem_limit: 1g
        # environment:
        #     JAVA_OPTS: " -Xms256m -Xmx512m"
        # ports:
        #     - 8094:8090

    share:
        image: alfresco/alfresco-share:$SHARE_TAG
        container_name: "${PROJECT_NAME}_share"
        mem_limit: 1g
        volumes:
            - ./volumes/logs/share:/usr/local/tomcat/logs
            - ./volumes/config/ext-share-config-custom.xml:/usr/local/tomcat/shared/classes/alfresco/web-extension/ext-share-config-custom.xml
        # environment:
        #     REPO_HOST: "alfresco"
        #     REPO_PORT: "8080"
        #     JAVA_OPTS: "
        #         -Xms500m
        #         -Xmx500m
        #         -Dalfresco.host=localhost
        #         -Dalfresco.port=8080
        #         -Dalfresco.context=alfresco
        #         -Dalfresco.protocol=http
        #         "

    postgres:
        image: postgres:$POSTGRES_TAG
        container_name: "${PROJECT_NAME}_postgres"
        mem_limit: 512m
        volumes:
        #    - ./volumes/data/postgres-data:/var/lib/postgresql/data
           - ./volumes/logs/postgres:/var/log/postgresql
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
        # command: postgres -c max_connections=300 -c log_min_messages=LOG
        # ports:
        #     - 5432:5432

    solr6:
        image: alfresco/alfresco-search-services:$ALFRESCO_SEARCH_TAG
        container_name: "${PROJECT_NAME}_solr6"
        mem_limit: 2g
        volumes:
            - ./volumes/data/solr-data:/opt/alfresco-search-services/data
        # environment:
        #     #Solr needs to know how to register itself with Alfresco
        #     - SOLR_ALFRESCO_HOST=alfresco
        #     - SOLR_ALFRESCO_PORT=8080
        #     #Alfresco needs to know how to call solr
        #     - SOLR_SOLR_HOST=solr6
        #     - SOLR_SOLR_PORT=8983
        #     #Create the default alfresco and archive cores
        #     - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
        #     #HTTP by default
        #     - ALFRESCO_SECURE_COMMS=none
        #     - "SOLR_JAVA_MEM=-Xms2g -Xmx2g"
        # ports:
        #     - 8083:8983 #Browser port

    activemq:
        image: alfresco/alfresco-activemq:$ACTIVEMQ_TAG
        container_name: "${PROJECT_NAME}_activemq"
        mem_limit: 1g
        # ports:
        #     - 8161:8161 # Web Console
        #     - 5672:5672 # AMQP
        #     - 61616:61616 # OpenWire
        #     - 61613:61613 # STOMP

    proxy:
        image: alfresco/acs-community-ngnix:$NGINX_TAG
        container_name: "${PROJECT_NAME}_proxy"
        mem_limit: 128m
        volumes:
            - ./volumes/config/nginx-default.conf:/etc/nginx/nginx.conf
            - ./volumes/config/nginx.conf:/etc/nginx/conf.d/default.conf
            # - ./volumes/config:/etc/nginx/conf.d
            - ./volumes/logs/nginx:/var/log/nginx
        # depends_on:
        #     - alfresco
        ports:
            - 9000:80
        # links:
        #     - alfresco
        #     - share
